function [result] = trainbayes(I, polymask)
    lab = rgb2lab(I);

    Lcomp = lab(:,:,1);
    Acomp = lab(:,:,2);
    Bcomp = lab(:,:,3);

    LcompRes = Lcomp(polymask);
    AcompRes = Acomp(polymask);
    BcompRes = Bcomp(polymask);

    [LallHist, LallEdges] = histcounts(Lcomp, 100);
    [LresHist, LresEdges] = histcounts(LcompRes, 100);
    [AallHist, AallEdges] = histcounts(Acomp, 255);
    [AresHist, AresEdges] = histcounts(AcompRes, 255);
    [BallHist, BallEdges] = histcounts(Bcomp, 255);
    [BresHist, BresEdges] = histcounts(BcompRes, 255);

    % save('trainedbayes.mat', ...
    %     'LallHist', 'LallEdges', 'LresHist', 'LresEdges', ...
    %     'AallHist', 'AallEdges', 'AresHist', 'AresEdges', ...
    %     'BallHist', 'BallEdges', 'BresHist', 'BresEdges');

    result = struct( ...
        'LallHist', {LallHist}, ...
        'LallEdges', {LallEdges}, ...
        'LresHist', {LresHist}, ...
        'LresEdges', {LresEdges}, ...
        'AallHist', {AallHist}, ...
        'AallEdges', {AallEdges}, ...
        'AresHist', {AresHist}, ...
        'AresEdges', {AresEdges}, ...
        'BallHist', {BallHist}, ...
        'BallEdges', {BallEdges}, ...
        'BresHist', {BresHist}, ...
        'BresEdges', {BresEdges});
end